name: Unit Tests

on: [push]

jobs: 
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Unit Test
        run: npm test ./testing/sum_tests.test.js
